//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.08 at 12:43:01 PM ECT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ec.gob.sri.ws.recepcion")
package ec.com.ups.electronic.util.wsdl.desarrollo.recepcion;
